US14 - Atualização da stastistic com as correções do P.O
fga-eps-mds/2023-2-CAPJu-Front pull request #12
Opened 2023-11-12 04:24 UTC by DanielRogs

## Issue

Closes fga-eps-mds/2023-2-CAPJu-Doc#20

## Descrição

Neste pull request, foram implementadas correções essenciais na funcionalidade, visando atender às solicitações específicas do Product Owner (P.O.). Dentre as melhorias realizadas, destaca-se a inclusão de uma nova coluna que exibe a data de vencimento, proporcionando uma visualização mais completa e intuitiva das informações. Além disso, a tabela foi reorganizada de forma a seguir uma ordem cronológica com base na data de vencimento, promovendo uma melhor organização e compreensão dos dados. A última contribuição consiste na persistência da pesquisa mesmo ao navegar para a página ShowProcess, garantindo uma experiência mais fluida e eficiente para o usuário, que pode explorar detalhes específicos sem perder o contexto inicial da busca.

## Revisão 

- [ ] Visualizar a data de vencimento na última coluna;
- [ ] Visualizar os processos na ordem de data de vencimento (Mais próximo ao mais distante);
- [ ] Depois de visualizar um processo, manter a pesquisa feita com as atualizações necessárias (permanência de dados);

## Pre-merge checklist 

- [ ] O Pull Request refere-se a um único assunto, um título claro e uma descrição em frases gramaticalmente corretas e completas.
- [ ] A ramificação está atualizada com a branch Develop.
- [ ] Os commits atendem o padrão especificado na política de contribuição.

2023-11-13 04:15 UTC, Denniel-sudo requested changes

2023-11-13 04:15 UTC, Denniel-sudo commented on src/pages/Statistics/StepDeadlineReports/index.tsx
> +      header: "Prazo do precesso na etapa",
Ajustar para "processo"

2023-11-13 04:18 UTC, Denniel-sudo commented
Ajustar a data desse campo para o formato brasileiro de dd/mm/yyyy
![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Front/assets/54074370/ee31ea68-c32e-4291-ad4d-e6deaeb19624)

2023-11-13 18:20 UTC, JongaMatos approved these changes
Sendo feitas as modificações solicitadas pelo Denniel, td certo.

2023-11-13 20:59 UTC, DanielRogs commented on src/pages/Statistics/StepDeadlineReports/index.tsx
> +      header: "Prazo do precesso na etapa",
@Denniel-sudo, não compreendi esse ajuste amigo

2023-11-13 21:00 UTC, DanielRogs commented
> Ajustar a data desse campo para o formato brasileiro de dd/mm/yyyy ![image](https://user-images.githubusercontent.com/54074370/282362473-ee31ea68-c32e-4291-ad4d-e6deaeb19624.png)

Já foi resolvido na PR da US14 no ProcessManagement

2023-11-13 23:25 UTC, DanielRogs commented
Correções efetuadas

2023-11-14 01:09 UTC, Denniel-sudo requested changes
Ajustar os testes

2023-11-19 00:31 UTC, DanielRogs commented
Testes ajustados

2023-11-19 16:44 UTC, Denniel-sudo approved these changes

2023-11-20 01:29 UTC, merged