Feat/22 processos concluidos por fluxo
fga-eps-mds/2023-2-CAPJu-Front pull request #2
Opened 2023-10-22 21:57 UTC by JongaMatos

## Issue

Closes fga-eps-mds/2023-1-CAPJu-Doc#22
Deve ser revisado em conjunto com o PR feito para o serviço process management.

## Descrição

# Critérios de aceitação
- [ ] Visualizar um relatório mostrando quais são os processos concluídos ou finalizados, de um fluxo, por período, na página de Estatísticas.
- [ ] Visualizar, por meio de um gráfico comparativo, a quantidade de processos concluídos e finalizados, de um fluxo, por período, na página de Estatísticas.

2023-10-23 02:28 UTC, WashingtonBispo approved these changes
Só tava dando uma leve travadinha quando mudava os filtros

2023-10-27 16:26 UTC, brendavsantos commented
O número de processos dentro de cada categoria (finalizados ou concluídos) está trocado. Criamos 3 concluídos e 1 interrompido e no gráfico mostra o contrário.

2023-10-27 16:27 UTC, brendavsantos requested changes
O número de processos dentro de cada categoria (finalizados ou concluídos) está trocado. Criamos 3 concluídos e 1 interrompido e no gráfico mostra o contrário.

2023-10-27 16:30 UTC, WashingtonBispo requested changes
O gráfico tá com as labels invertidas no gráfico e os status também na tabela do relatório.
Se for rápido seria bom evitar gerar o gráfico enquanto a pessoa digita a data pois está dando umas travadinhas.

2023-10-27 18:47 UTC, WashingtonBispo approved these changes
ok

2023-10-27 22:29 UTC, brendavsantos approved these changes

2023-10-28 00:48 UTC, merged