US11 e US12 -  filtrar processo etapa fluxo
fga-eps-mds/2023-2-CAPJu-Front pull request #21
Opened 2023-11-23 01:37 UTC by AmandaaMoura

## Issue

US11 - Filtrar processo por etapa
US12 - Filtrar processo por fluxo

## Descrição

US 11 - Eu, como estagiário, servidor, diretor, juiz, e administrador, gostaria de filtrar os processos por meio das Etapas para poder visualizar quais processos se encontram em uma mesma Etapa.

US12 - Eu, como estagiário, servidor, diretor, juiz, e administrador, gostaria de filtrar os processos por meio dos Fluxos para poder visualizar quais processos fazem parte do mesmo Fluxo.

## Revisão 

- [ ] Poder visualizar um campo de busca com seleções
- [ ] Ao clicar no filtro escolhido, poder ver, entre as opções, "Etapa"
- [ ] Poder selecionar uma das opções e fazer uma busca a partir dela
- [ ] Obter o resultado de quais processos estão em determinado Etapa

## Pre-merge checklist 

- [ ] O Pull Request refere-se a um único assunto, um título claro e uma descrição em frases gramaticalmente corretas e completas.
- [ ] A ramificação está atualizada com a branch Develop.
- [ ] Os commits atendem o padrão especificado na política de contribuição.

2023-11-23 02:19 UTC, WashingtonBispo requested changes
![image](https://github.com/fga-eps-mds/2023-2-CAPJu-Front/assets/43673797/6e08908c-60db-445a-8014-2d98bdd030df)
ícone quebrado

2023-11-23 20:15 UTC, brendavsantos approved these changes

2023-11-23 21:49 UTC, WashingtonBispo approved these changes
LGTM

2023-11-23 21:54 UTC, WashingtonBispo requested changes
O lint quebrou na verdade

2023-11-24 21:10 UTC, WashingtonBispo approved these changes

2023-11-24 21:21 UTC, merged