09 atualizacao visualizacao etapa processo
fga-eps-mds/2023-2-CAPJu-Front pull request #9
Opened 2023-11-06 19:45 UTC by DanielRogs

## Issue

Closes [#19 - US09 - Atualização e visualização de status do processo](https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/issues/19)
## Descrição

Neste Pull Request, foram implementadas as alterações necessárias para atender aos requisitos da US09. As modificações abrangeram a atualização das cores e do texto em botões, pop-ups e elementos de interface que faziam referência aos diversos estados do processo, incluindo a transição de "Finalizados" para "Concluídos" e "Arquivados" para "Interrompidos". Além disso, foram incorporadas outras mudanças que se originaram da revisão e validação conduzida por Wellington, todas devidamente ajustadas e integradas a este Pull Request.

Os testes da página foram adaptados para acomodar essas mudanças e garantir que a página Processes esteja em conformidade com as novas referências. Isso pode ser exemplificado no seguinte trecho do código:

**In src/pages/__tests__/Processes.test.tsx:**
```
 it("toggles 'archived/finished processes' checkbox correctly", async () => {
    const button = screen.getByText(
      "Mostrar processos interrompidos/concluídos"
    );
```

Contudo, um dos problemas, ainda desconhecido, ocorre na verificação dos testes no momento do commit:

```
Run export NODE_OPTIONS="--max_old_space_size=4096"
yarn run v1.22.19
$ vitest --silent

 RUN  v0.31.4 /home/runner/work/2023-2-CAPJu-Front/2023-2-CAPJu-Front

 ✓ src/pages/__tests__/Login.test.tsx  (10 tests) 1426ms
 ✓ src/pages/__tests__/Stages.test.tsx  (4 tests) 4153ms
 ✓ src/pages/__tests__/Units.test.tsx  (4 tests) 4[13](https://github.com/fga-eps-mds/2023-2-CAPJu-Front/actions/runs/6738583613/job/18318463143#step:6:14)9ms
 ✓ src/pages/__tests__/Flows.test.tsx  (3 tests) 2591ms
 ✓ src/pages/__tests__/ViewProcess.test.tsx  (3 tests) 960ms
 ✓ src/pages/__tests__/Signup.test.tsx  (3 tests) 946ms
 ✓ src/components/__tests__/Tutorial.test.tsx  (2 tests) 575ms
 ✓ src/components/__tests__/Flow.test.tsx  (6 tests) 346ms
 ✓ src/pages/__tests__/PasswordEdition.test.tsx  (1 test) 608ms
 ✓ src/pages/__tests__/AccountEdition.test.tsx  (1 test) 362ms
 ✓ src/pages/__tests__/EmailEdition.test.tsx  (1 test) 399ms
 ✓ src/pages/__tests__/About.test.tsx  (3 tests) 663ms
 ✓ src/pages/__tests__/ForgotPassword.test.tsx  (1 test) 259ms
 ✓ src/__tests__/App.test.tsx  (1 test) 275ms

⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
Error: Worker terminated due to reaching memory limit: JS heap out of memory
 ❯ new NodeError node:internal/errors:387:5
 ❯ Worker.[kOnExit] node:internal/worker:285:26
 ❯ Worker.<computed>.onexit node:internal/worker:202:20

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: {
  "code": "ERR_WORKER_OUT_OF_MEMORY",
}
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 Test Files  [14](https://github.com/fga-eps-mds/2023-2-CAPJu-Front/actions/runs/6738583613/job/18318463143#step:6:15) passed ([15](https://github.com/fga-eps-mds/2023-2-CAPJu-Front/actions/runs/6738583613/job/18318463143#step:6:16))
      Tests  48 passed (53)
     Errors  1 error
   Start at  21:50:01
   Duration  462.26s (transform 960ms, setup 1ms, collect 27.71s, tests [17](https://github.com/fga-eps-mds/2023-2-CAPJu-Front/actions/runs/6738583613/job/18318463143#step:6:18).70s, environment 5.97s, prepare 1.21s)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

Mesmo com a aprovação em todos os testes do Front-End, há uma falha de memória alocada para execução dos testes. Esse problema pode ser visto nos logs de teste do último commit desta ramificação: [Clique Aqui](https://github.com/fga-eps-mds/2023-2-CAPJu-Front/actions/runs/6738583613/job/18318463143).

Este problema não foi corrigido nesta PR.

## Revisão 

- [ ] Ao clicar no botão "Interromper Processo" espera-se que o status do processo mude para "Interrompido"
- [ ] Ao clicar no botão "Concluir Processo" espera-se que o status do processo mude para "Concluído" 
- [ ] Ao clicar no botão "Reativar processo" espera-se que o status do processo mude para "Em andamento"

**Conseguir visualizar todos os tipos de status dos processos**
**Na tabela dentro da página dos processos:**
   - [ ] O processo no status "Não Iniciado";
   - [ ] O processo no status "Em Andamento";
   - [ ] O processo no status "Interrompido";
   - [ ] O processo no status "Concluído".
 
**Na informação "status" dentro da página detalhada do processo selecionado:**
   - [ ] O processo no status "Não Iniciado";
   - [ ] O processo no status "Em Andamento";
   - [ ] O processo no status "Interrompido";
   - [ ] O processo no status "Concluído".

## Pre-merge checklist 

- [ ] O Pull Request refere-se a um único assunto, um título claro e uma descrição em frases gramaticalmente corretas e completas.
- [ ] A ramificação está atualizada com a branch Develop.
- [ ] Os commits atendem o padrão especificado na política de contribuição.

2023-11-13 02:28 UTC, Denniel-sudo approved these changes

2023-11-13 21:29 UTC, brendavsantos approved these changes

2023-11-20 19:31 UTC, Denniel-sudo requested changes
Arrumar pipeline, está quebrando ela toda

2023-11-20 19:38 UTC, DanielRogs commented
Eu sei :-: Quebraram ela aq, já vamos arrumar

2023-11-20 21:40 UTC, closed without merging